In [8]:
from pathlib import Path

data_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted"
)

yaml_files = list(data_folder.glob("*.yaml"))

print("Total YAML files:", len(yaml_files))
print("\nFirst 10 files:")

for file in yaml_files[:10]:
    print(file.name)


import yaml
from pathlib import Path

# Select the first YAML file
sample_file = yaml_files[0]

# Read the match data
with open(sample_file, "r", encoding="utf-8") as file:
    match_data = yaml.safe_load(file)

print("File name:", sample_file.name)

print("\nTop-level keys:")
print(match_data.keys())

print("\nMatch information:")
print(match_data["info"].keys())

print("\nTeams:")
print(match_data["info"]["teams"])

print("\nDates:")
print(match_data["info"]["dates"])

print("\nVenue:")
print(match_data["info"].get("venue", "Not available"))


import yaml
import pandas as pd
from datetime import date

matches = []

for file_path in yaml_files:
    with open(file_path, "r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    info = data.get("info", {})
    match_dates = info.get("dates", [])

    if not match_dates:
        continue

    match_date = date.fromisoformat(str(match_dates[0]))

    # Men's T20 World Cup 2024 dates
    if date(2024, 6, 1) <= match_date <= date(2024, 6, 29):
        matches.append({
            "file_name": file_path.name,
            "date": match_date,
            "team1": info.get("teams", [None, None])[0],
            "team2": info.get("teams", [None, None])[1],
            "venue": info.get("venue", "Unknown"),
            "match_type": info.get("match_type"),
            "gender": info.get("gender")
        })

matches_df = pd.DataFrame(matches)

print("Matches found in date range:", len(matches_df))
display(matches_df.head(10))


from pathlib import Path

output_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned"
)

output_folder.mkdir(parents=True, exist_ok=True)

matches_df.to_csv(
    output_folder / "matches_date_candidates.csv",
    index=False
)

print("Candidate match list saved successfully.")
print("File:", output_folder / "matches_date_candidates.csv")
print("Total records:", len(matches_df))

Total YAML files: 230

First 10 files:
1273712.yaml
1273713.yaml
1273714.yaml
1273715.yaml
1273716.yaml
1273717.yaml
1273718.yaml
1273719.yaml
1273720.yaml
1273721.yaml
File name: 1273712.yaml

Top-level keys:
dict_keys(['meta', 'info', 'innings'])

Match information:
dict_keys(['balls_per_over', 'city', 'dates', 'gender', 'match_type', 'match_type_number', 'outcome', 'overs', 'player_of_match', 'players', 'registry', 'teams', 'toss', 'umpires', 'venue', 'team_type'])

Teams:
['Papua New Guinea', 'Oman']

Dates:
['2021-10-17']

Venue:
Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)
Matches found in date range: 44

,file_name,date,team1,team2,venue,match_type,gender
0,1415701.yaml,2024-06-01,Canada,United States of America,"Grand Prairie Stadium, Dallas",T20,male
1,1415702.yaml,2024-06-02,Papua New Guinea,West Indies,"Providence Stadium, Guyana",T20,male
2,1415703.yaml,2024-06-02,Oman,Namibia,"Kensington Oval, Bridgetown, Barbados",T20,male
3,1415704.yaml,2024-06-03,Sri Lanka,South Africa,"Nassau County International Cricket Stadium, N...",T20,male
4,1415706.yaml,2024-06-04,Scotland,England,"Kensington Oval, Bridgetown, Barbados",T20,male
5,1415707.yaml,2024-06-04,Nepal,Netherlands,"Grand Prairie Stadium, Dallas",T20,male
6,1415708.yaml,2024-06-05,Ireland,India,"Nassau County International Cricket Stadium, N...",T20,male
7,1415709.yaml,2024-06-05,Papua New Guinea,Uganda,"Providence Stadium, Guyana",T20,male
8,1415710.yaml,2024-06-05,Australia,Oman,"Kensington Oval, Bridgetown, Barbados",T20,male
9,1415711.yaml,2024-06-06,Pakistan,United States of America,"Grand Prairie Stadium, Dallas",T20,male

Candidate match list saved successfully.
File: C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned\matches_date_candidates.csv
Total records: 44

In [9]:

print("Dates covered:")
print(matches_df["date"].min(), "to", matches_df["date"].max())

print("\nMatches by date:")
print(
    matches_df.groupby("date")
    .size()
    .sort_index()
    .to_string()
)

print("\nTeams appearing in the candidate matches:")
teams = sorted(
    set(matches_df["team1"].dropna())
    | set(matches_df["team2"].dropna())
)

for team in teams:
    print(team)

Dates covered:
2024-06-01 to 2024-06-29

Matches by date:
date
2024-06-01    1
2024-06-02    2
2024-06-03    1
2024-06-04    2
2024-06-05    3
2024-06-06    2
2024-06-07    2
2024-06-08    3
2024-06-09    2
2024-06-10    1
2024-06-11    2
2024-06-12    2
2024-06-13    2
2024-06-14    2
2024-06-15    2
2024-06-16    3
2024-06-17    1
2024-06-19    2
2024-06-20    1
2024-06-21    2
2024-06-22    1
2024-06-23    2
2024-06-24    1
2024-06-27    1
2024-06-29    1

Teams appearing in the candidate matches:
Australia
Bangladesh
Canada
England
India
Ireland
Namibia
Nepal
Netherlands
New Zealand
Oman
Pakistan
Papua New Guinea
Scotland
South Africa
Sri Lanka
Uganda
United States of America
West Indies

In [10]:

# Inspect tournament metadata from the first candidate
sample_name = matches_df.iloc[0]["file_name"]

sample_path = next(
    file for file in yaml_files
    if file.name == sample_name
)

with open(sample_path, "r", encoding="utf-8") as file:
    sample_data = yaml.safe_load(file)

print("File:", sample_name)
print("\nMatch metadata:")
print(sample_data["info"])

print("\nAvailable metadata fields:")
print(list(sample_data["info"].keys()))

File: 1415701.yaml

Match metadata:
{'balls_per_over': 6, 'city': 'Dallas', 'dates': ['2024-06-01'], 'gender': 'male', 'match_type': 'T20', 'match_type_number': 2632, 'outcome': {'winner': 'United States of America', 'by': {'wickets': 7}}, 'overs': 20, 'player_of_match': ['Aaron Jones'], 'players': {'Canada': ['A Johnson', 'NS Dhaliwal', 'Pargat Singh', 'NR Kirton', 'S Movva', 'DS Bajwa', 'D Heyliger', 'Saad Bin Zafar', 'N Dutta', 'Kaleem Sana', 'JOA Gordon'], 'United States of America': ['SR Taylor', 'MD Patel', 'AGS Gous', 'Aaron Jones', 'CJ Anderson', 'NR Kumar', 'Harmeet Singh', 'SC van Schalkwyk', 'Jasdeep Singh', 'SN Netravalkar', 'Ali Khan']}, 'registry': {'people': {'A Johnson': 'a28a7fba', 'AGS Gous': 'd1305df0', 'Aaron Jones': '17aa4f1d', 'Ali Khan': 'b0eaaac6', 'CJ Anderson': '8abdf100', 'D Heyliger': 'f8c72766', 'DS Bajwa': 'e3540b8c', 'Harmeet Singh': '0bf15e52', 'JOA Gordon': 'bb9b51f4', 'Jasdeep Singh': '5ec41cd7', 'Kaleem Sana': '14810ee7', 'L Rusere': '6a4734ae', 'MD Patel': '25d7f1ac', 'N Dutta': 'e258a603', 'NR Kirton': '6b75c2b1', 'NR Kumar': 'b3bad3f2', 'NS Dhaliwal': 'cbabd6ad', 'Pargat Singh': 'd2e67105', 'RB Richardson': '410e2f12', 'RK Illingworth': '20672246', 'S Movva': 'ee229588', 'SC van Schalkwyk': '97b0e4ff', 'SJ Nogajski': '9b3f9323', 'SN Netravalkar': 'c8a3f688', 'SR Taylor': 'a9231c3f', 'Saad Bin Zafar': 'f28a60e0', 'Sharfuddoula': '63896abb'}}, 'teams': ['Canada', 'United States of America'], 'toss': {'winner': 'United States of America', 'decision': 'field'}, 'umpires': ['RK Illingworth', 'Sharfuddoula'], 'venue': 'Grand Prairie Stadium, Dallas', 'team_type': 'international'}

Available metadata fields:
['balls_per_over', 'city', 'dates', 'gender', 'match_type', 'match_type_number', 'outcome', 'overs', 'player_of_match', 'players', 'registry', 'teams', 'toss', 'umpires', 'venue', 'team_type']

In [13]:

output_folder = (
    Path(r"C:\Users\reddy\OneDrive\Documents"
         r"\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned")
)

output_folder.mkdir(parents=True, exist_ok=True)

matches_df.to_csv(
    output_folder / "matches_date_candidates.csv",
    index=False
)

print("Saved candidate matches:", len(matches_df))

output_folder = (
    Path(r"C:\Users\reddy\OneDrive\Documents"
         r"\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned")
)

output_folder.mkdir(parents=True, exist_ok=True)

matches_df.to_csv(
    output_folder / "matches_date_candidates.csv",
    index=False
)

print("Saved:", output_folder / "matches_date_candidates.csv")

Saved candidate matches: 44
Saved: C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned\matches_date_candidates.csv

In [14]:

# Display all candidate matches in a readable format

print("Total candidate matches:", len(matches_df))

display(
    matches_df[
        ["file_name", "date", "team1", "team2", "venue"]
    ]
    .sort_values(["date", "team1"])
    .reset_index(drop=True)
)

Total candidate matches: 44

,file_name,date,team1,team2,venue
0,1415701.yaml,2024-06-01,Canada,United States of America,"Grand Prairie Stadium, Dallas"
1,1415703.yaml,2024-06-02,Oman,Namibia,"Kensington Oval, Bridgetown, Barbados"
2,1415702.yaml,2024-06-02,Papua New Guinea,West Indies,"Providence Stadium, Guyana"
3,1415704.yaml,2024-06-03,Sri Lanka,South Africa,"Nassau County International Cricket Stadium, N..."
4,1415707.yaml,2024-06-04,Nepal,Netherlands,"Grand Prairie Stadium, Dallas"
5,1415706.yaml,2024-06-04,Scotland,England,"Kensington Oval, Bridgetown, Barbados"
6,1415710.yaml,2024-06-05,Australia,Oman,"Kensington Oval, Bridgetown, Barbados"
7,1415708.yaml,2024-06-05,Ireland,India,"Nassau County International Cricket Stadium, N..."
8,1415709.yaml,2024-06-05,Papua New Guinea,Uganda,"Providence Stadium, Guyana"
9,1415712.yaml,2024-06-06,Namibia,Scotland,"Kensington Oval, Bridgetown, Barbados"
10,1415711.yaml,2024-06-06,Pakistan,United States of America,"Grand Prairie Stadium, Dallas"
11,1415713.yaml,2024-06-07,Canada,Ireland,"Nassau County International Cricket Stadium, N..."
12,1415715.yaml,2024-06-07,Sri Lanka,Bangladesh,"Grand Prairie Stadium, Dallas"
13,1415717.yaml,2024-06-08,Australia,England,"Kensington Oval, Bridgetown, Barbados"
14,1415716.yaml,2024-06-08,Netherlands,South Africa,"Nassau County International Cricket Stadium, N..."
15,1415718.yaml,2024-06-08,West Indies,Uganda,"Providence Stadium, Guyana"
16,1415719.yaml,2024-06-09,India,Pakistan,"Nassau County International Cricket Stadium, N..."
17,1415720.yaml,2024-06-09,Oman,Scotland,"Sir Vivian Richards Stadium, North Sound, Antigua"
18,1415721.yaml,2024-06-10,South Africa,Bangladesh,"Nassau County International Cricket Stadium, N..."
19,1415722.yaml,2024-06-11,Canada,Pakistan,"Nassau County International Cricket Stadium, N..."
20,1415724.yaml,2024-06-11,Namibia,Australia,"Sir Vivian Richards Stadium, North Sound, Antigua"
21,1415725.yaml,2024-06-12,United States of America,India,"Nassau County International Cricket Stadium, N..."
22,1415726.yaml,2024-06-12,West Indies,New Zealand,"Brian Lara Stadium, Tarouba, Trinidad"
23,1415727.yaml,2024-06-13,Bangladesh,Netherlands,"Arnos Vale Ground, Kingstown, St Vincent"
24,1415728.yaml,2024-06-13,Oman,England,"Sir Vivian Richards Stadium, North Sound, Antigua"
25,1415731.yaml,2024-06-14,South Africa,Nepal,"Arnos Vale Ground, Kingstown, St Vincent"
26,1415732.yaml,2024-06-14,Uganda,New Zealand,"Brian Lara Stadium, Tarouba, Trinidad"
27,1415734.yaml,2024-06-15,England,Namibia,"Sir Vivian Richards Stadium, North Sound, Antigua"
28,1415735.yaml,2024-06-15,Scotland,Australia,"Daren Sammy National Cricket Stadium, Gros Isl..."
29,1415737.yaml,2024-06-16,Bangladesh,Nepal,"Arnos Vale Ground, Kingstown, St Vincent"
30,1415736.yaml,2024-06-16,Ireland,Pakistan,Central Broward Regional Park Stadium Turf Gro...
31,1415738.yaml,2024-06-16,Sri Lanka,Netherlands,"Daren Sammy National Cricket Stadium, Gros Isl..."
32,1415739.yaml,2024-06-17,Papua New Guinea,New Zealand,"Brian Lara Stadium, Tarouba, Trinidad"
33,1415741.yaml,2024-06-19,South Africa,United States of America,"Sir Vivian Richards Stadium, North Sound, Antigua"
34,1415742.yaml,2024-06-19,West Indies,England,"Daren Sammy National Cricket Stadium, Gros Isl..."
35,1415744.yaml,2024-06-20,Bangladesh,Australia,"Sir Vivian Richards Stadium, North Sound, Antigua"
36,1415745.yaml,2024-06-21,South Africa,England,"Daren Sammy National Cricket Stadium, Gros Isl..."
37,1415746.yaml,2024-06-21,United States of America,West Indies,"Kensington Oval, Bridgetown, Barbados"
38,1415747.yaml,2024-06-22,India,Bangladesh,"Sir Vivian Richards Stadium, North Sound, Antigua"
39,1415749.yaml,2024-06-23,United States of America,England,"Kensington Oval, Bridgetown, Barbados"
40,1415750.yaml,2024-06-23,West Indies,South Africa,"Sir Vivian Richards Stadium, North Sound, Antigua"
41,1415751.yaml,2024-06-24,India,Australia,"Daren Sammy National Cricket Stadium, Gros Isl..."
42,1415754.yaml,2024-06-27,India,England,"Providence Stadium, Guyana"
43,1415755.yaml,2024-06-29,India,South Africa,"Kensington Oval, Bridgetown, Barbados"

In [15]:

import yaml
import pandas as pd
from pathlib import Path

# Output folders
project_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics"
)

cleaned_folder = project_folder / "02_Data" / "Cleaned"
cleaned_folder.mkdir(parents=True, exist_ok=True)

match_rows = []
delivery_rows = []

# Process only the candidate match files
candidate_names = set(matches_df["file_name"])

for file_path in yaml_files:
    if file_path.name not in candidate_names:
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    info = data.get("info", {})
    teams = info.get("teams", [])
    dates = info.get("dates", [])

    # Match-level information
    match_rows.append({
        "match_id": file_path.stem,
        "date": dates[0] if dates else None,
        "team1": teams[0] if len(teams) > 0 else None,
        "team2": teams[1] if len(teams) > 1 else None,
        "venue": info.get("venue"),
        "city": info.get("city"),
        "gender": info.get("gender"),
        "match_type": info.get("match_type")
    })

    # Ball-by-ball information
    for innings_number, innings in enumerate(
        data.get("innings", []), start=1
    ):
        batting_team = innings.get("team")

        for over in innings.get("overs", []):
            over_number = over.get("over")

            for ball_number, delivery in enumerate(
                over.get("deliveries", []), start=1
            ):
                batter = delivery.get("batter")
                bowler = delivery.get("bowler")
                extras = delivery.get("extras", {})
                wickets = delivery.get("wickets", [])

                batter_runs = delivery.get(
                    "runs", {}
                ).get("batter", 0)

                total_runs = delivery.get(
                    "runs", {}
                ).get("total", 0)

                delivery_rows.append({
                    "match_id": file_path.stem,
                    "innings": innings_number,
                    "batting_team": batting_team,
                    "over": over_number,
                    "ball_in_over": ball_number,
                    "batter": batter,
                    "bowler": bowler,
                    "batter_runs": batter_runs,
                    "total_runs": total_runs,
                    "wide_runs": extras.get("wides", 0),
                    "no_ball_runs": extras.get("noballs", 0),
                    "byes": extras.get("byes", 0),
                    "leg_byes": extras.get("legbyes", 0),
                    "penalty_runs": extras.get("penalty", 0),
                    "wicket_count": len(wickets),
                    "wicket_players": ", ".join(
                        w.get("player_out", "") for w in wickets
                    )
                })

matches_export = pd.DataFrame(match_rows)
deliveries_export = pd.DataFrame(delivery_rows)

matches_export.to_csv(
    cleaned_folder / "matches.csv", index=False
)

deliveries_export.to_csv(
    cleaned_folder / "deliveries.csv", index=False
)

print("Matches exported:", len(matches_export))
print("Deliveries exported:", len(deliveries_export))
print("Files saved in:", cleaned_folder)

Matches exported: 44
Deliveries exported: 0
Files saved in: C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned

In [16]:

# Inspect the structure of one match file

sample_name = matches_df.iloc[0]["file_name"]

sample_path = next(
    file for file in yaml_files
    if file.name == sample_name
)

with open(sample_path, "r", encoding="utf-8") as file:
    sample_data = yaml.safe_load(file)

print("File:", sample_name)
print("Top-level keys:", sample_data.keys())
print("Number of innings:", len(sample_data.get("innings", [])))

if sample_data.get("innings"):
    first_innings = sample_data["innings"][0]

    print("\nFirst innings keys:")
    print(first_innings.keys())

    print("\nFirst innings data sample:")
    print(first_innings)

File: 1415701.yaml
Top-level keys: dict_keys(['meta', 'info', 'innings'])
Number of innings: 2

First innings keys:
dict_keys(['1st innings'])

First innings data sample:

In [18]:

import yaml
import pandas as pd
from pathlib import Path

project_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics"
)

cleaned_folder = project_folder / "02_Data" / "Cleaned"
cleaned_folder.mkdir(parents=True, exist_ok=True)

match_rows = []
delivery_rows = []

candidate_names = set(matches_df["file_name"])

for file_path in yaml_files:
    if file_path.name not in candidate_names:
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    info = data.get("info", {})
    teams = info.get("teams", [])
    dates = info.get("dates", [])

    match_id = file_path.stem

    match_rows.append({
        "match_id": match_id,
        "date": dates[0] if dates else None,
        "team1": teams[0] if len(teams) > 0 else None,
        "team2": teams[1] if len(teams) > 1 else None,
        "venue": info.get("venue"),
        "city": info.get("city"),
        "gender": info.get("gender"),
        "match_type": info.get("match_type")
    })

    # This archive stores each innings as a named dictionary.
    for innings_number, innings_entry in enumerate(
        data.get("innings", []), start=1
    ):
        innings_name, innings_data = next(iter(innings_entry.items()))

        batting_team = innings_data.get("team")
        deliveries = innings_data.get("deliveries", [])

        for delivery_item in deliveries:
            # Each delivery is a dictionary keyed by over.ball
            ball_label, ball_data = next(iter(delivery_item.items()))

            extras = ball_data.get("extras", {})
            runs = ball_data.get("runs", {})
            wickets = ball_data.get("wicket", [])

            delivery_rows.append({
                "match_id": match_id,
                "innings": innings_number,
                "innings_name": innings_name,
                "batting_team": batting_team,
                "ball_label": str(ball_label),
                "batter": ball_data.get("batter"),
                "bowler": ball_data.get("bowler"),
                "batter_runs": runs.get("batter", 0),
                "total_runs": runs.get("total", 0),
                "wide_runs": extras.get("wides", 0),
                "no_ball_runs": extras.get("noballs", 0),
                "byes": extras.get("byes", 0),
                "leg_byes": extras.get("legbyes", 0),
                "penalty_runs": extras.get("penalty", 0),
                "wicket_count": len(wickets),
                "wicket_players": ", ".join(
                    str(wicket.get("player_out", ""))
                    for wicket in wickets
                    if isinstance(wicket, dict)
                )
            })

matches_export = pd.DataFrame(match_rows)
deliveries_export = pd.DataFrame(delivery_rows)

matches_export.to_csv(
    cleaned_folder / "matches.csv", index=False
)

deliveries_export.to_csv(
    cleaned_folder / "deliveries.csv", index=False
)

print("Matches exported:", len(matches_export))
print("Deliveries exported:", len(deliveries_export))
print("Output folder:", cleaned_folder)

display(deliveries_export.head())

Matches exported: 44
Deliveries exported: 9722
Output folder: C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned

,match_id,innings,innings_name,batting_team,ball_label,batter,bowler,batter_runs,total_runs,wide_runs,no_ball_runs,byes,leg_byes,penalty_runs,wicket_count,wicket_players
0,1415701,1,1st innings,Canada,0.1,None,Ali Khan,0,4,0,0,0,0,0,0,
1,1415701,1,1st innings,Canada,0.2,None,Ali Khan,0,0,0,0,0,0,0,0,
2,1415701,1,1st innings,Canada,0.3,None,Ali Khan,0,1,0,0,0,1,0,0,
3,1415701,1,1st innings,Canada,0.4,None,Ali Khan,0,0,0,0,0,0,0,0,
4,1415701,1,1st innings,Canada,0.5,None,Ali Khan,0,0,0,0,0,0,0,0,

In [19]:

import pandas as pd
from pathlib import Path

project_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics"
)

cleaned_folder = project_folder / "02_Data" / "Cleaned"

matches = pd.read_csv(cleaned_folder / "matches.csv")
deliveries = pd.read_csv(cleaned_folder / "deliveries.csv")

print("Matches:", matches.shape)
print("Deliveries:", deliveries.shape)

print("\nDelivery columns:")
print(deliveries.columns.tolist())

print("\nMissing values:")
print(
    deliveries.isnull()
    .sum()
    .sort_values(ascending=False)
)

print("\nDuplicate delivery rows:", deliveries.duplicated().sum())

print("\nSample deliveries:")
display(deliveries.head(10))

Matches: (44, 8)
Deliveries: (9722, 16)

Delivery columns:
['match_id', 'innings', 'innings_name', 'batting_team', 'ball_label', 'batter', 'bowler', 'batter_runs', 'total_runs', 'wide_runs', 'no_ball_runs', 'byes', 'leg_byes', 'penalty_runs', 'wicket_count', 'wicket_players']

Missing values:
batter            9722
wicket_players    9722
innings_name         0
match_id             0
batting_team         0
ball_label           0
bowler               0
innings              0
batter_runs          0
total_runs           0
no_ball_runs         0
wide_runs            0
byes                 0
leg_byes             0
penalty_runs         0
wicket_count         0
dtype: int64

Duplicate delivery rows: 0

Sample deliveries:

,match_id,innings,innings_name,batting_team,ball_label,batter,bowler,batter_runs,total_runs,wide_runs,no_ball_runs,byes,leg_byes,penalty_runs,wicket_count,wicket_players
0,1415701,1,1st innings,Canada,0.1,NaN,Ali Khan,0,4,0,0,0,0,0,0,NaN
1,1415701,1,1st innings,Canada,0.2,NaN,Ali Khan,0,0,0,0,0,0,0,0,NaN
2,1415701,1,1st innings,Canada,0.3,NaN,Ali Khan,0,1,0,0,0,1,0,0,NaN
3,1415701,1,1st innings,Canada,0.4,NaN,Ali Khan,0,0,0,0,0,0,0,0,NaN
4,1415701,1,1st innings,Canada,0.5,NaN,Ali Khan,0,0,0,0,0,0,0,0,NaN
5,1415701,1,1st innings,Canada,0.6,NaN,Ali Khan,0,1,0,0,0,0,0,0,NaN
6,1415701,1,1st innings,Canada,1.1,NaN,SN Netravalkar,0,0,0,0,0,0,0,0,NaN
7,1415701,1,1st innings,Canada,1.2,NaN,SN Netravalkar,0,4,0,0,0,0,0,0,NaN
8,1415701,1,1st innings,Canada,1.3,NaN,SN Netravalkar,0,1,0,0,0,0,0,0,NaN
9,1415701,1,1st innings,Canada,1.4,NaN,SN Netravalkar,0,1,0,0,0,0,0,0,NaN

In [20]:

# Check match coverage
print("Matches in matches.csv:", matches["match_id"].nunique())
print("Matches in deliveries.csv:", deliveries["match_id"].nunique())

# Check player fields
print("\nMissing batters:", deliveries["batter"].isna().sum())
print("Missing bowlers:", deliveries["bowler"].isna().sum())

# Check run values
print("\nNegative batter runs:",
      (deliveries["batter_runs"] < 0).sum())

print("Negative total runs:",
      (deliveries["total_runs"] < 0).sum())

# Check innings and teams
print("\nInnings distribution:")
print(deliveries["innings"].value_counts().sort_index())

print("\nDeliveries per match:")
display(
    deliveries.groupby("match_id")
    .size()
    .describe()
)

Matches in matches.csv: 44
Matches in deliveries.csv: 44

Missing batters: 9722
Missing bowlers: 0

Negative batter runs: 0
Negative total runs: 0

Innings distribution:
innings
1    5232
2    4461
3      15
4      14
Name: count, dtype: int64

Deliveries per match:

count     44.000000
mean     220.954545
std       44.287619
min       62.000000
25%      202.500000
50%      241.000000
75%      248.250000
max      270.000000
dtype: float64

In [21]:

# Inspect one raw delivery directly from the source YAML

sample_name = matches_df.iloc[0]["file_name"]

sample_path = next(
    file for file in yaml_files
    if file.name == sample_name
)

with open(sample_path, "r", encoding="utf-8") as file:
    sample_data = yaml.safe_load(file)

first_innings = sample_data["innings"][0]
innings_name, innings_data = next(iter(first_innings.items()))

first_delivery = innings_data["deliveries"][0]
ball_label, ball_data = next(iter(first_delivery.items()))

print("Innings name:", innings_name)
print("Ball label:", ball_label)

print("\nRaw delivery dictionary:")
print(ball_data)

print("\nDelivery keys:")
print(ball_data.keys())

print("\nBatter value:")
print(ball_data.get("batter"))

print("\nBowler value:")
print(ball_data.get("bowler"))

Innings name: 1st innings
Ball label: 0.1

Raw delivery dictionary:
{'actual_delivery': '0.1', 'non_striker': 'NS Dhaliwal', 'bowler': 'Ali Khan', 'runs': {'extras': 0, 'total': 4, 'batsman': 4}, 'batsman': 'A Johnson'}

Delivery keys:
dict_keys(['actual_delivery', 'non_striker', 'bowler', 'runs', 'batsman'])

Batter value:
None

Bowler value:
Ali Khan

In [22]:

import yaml
import pandas as pd
from pathlib import Path

project_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics"
)

cleaned_folder = project_folder / "02_Data" / "Cleaned"
cleaned_folder.mkdir(parents=True, exist_ok=True)

delivery_rows = []
candidate_names = set(matches_df["file_name"])

for file_path in yaml_files:
    if file_path.name not in candidate_names:
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    match_id = file_path.stem

    for innings_number, innings_entry in enumerate(
        data.get("innings", []), start=1
    ):
        innings_name, innings_data = next(
            iter(innings_entry.items())
        )

        batting_team = innings_data.get("team")

        for delivery_item in innings_data.get("deliveries", []):
            ball_label, ball_data = next(iter(delivery_item.items()))

            runs = ball_data.get("runs", {})
            extras = ball_data.get("extras", {})
            wickets = ball_data.get("wicket", [])

            # Normalize wicket records
            if isinstance(wickets, dict):
                wickets = [wickets]
            elif not isinstance(wickets, list):
                wickets = []

            wicket_players = []
            for wicket in wickets:
                if isinstance(wicket, dict):
                    player = wicket.get("player_out")
                    if player:
                        wicket_players.append(player)

            delivery_rows.append({
                "match_id": match_id,
                "innings": innings_number,
                "innings_name": innings_name,
                "batting_team": batting_team,
                "ball_label": str(ball_label),
                "batter": ball_data.get("batsman"),
                "non_striker": ball_data.get("non_striker"),
                "bowler": ball_data.get("bowler"),
                "batter_runs": runs.get("batsman", 0),
                "total_runs": runs.get("total", 0),
                "extra_runs": runs.get("extras", 0),
                "wide_runs": extras.get("wides", 0),
                "no_ball_runs": extras.get("noballs", 0),
                "byes": extras.get("byes", 0),
                "leg_byes": extras.get("legbyes", 0),
                "penalty_runs": extras.get("penalty", 0),
                "wicket_count": len(wickets),
                "wicket_players": ", ".join(wicket_players)
            })

deliveries_export = pd.DataFrame(delivery_rows)

deliveries_export.to_csv(
    cleaned_folder / "deliveries.csv",
    index=False
)

print("Deliveries exported:", len(deliveries_export))
print("Missing batters:", deliveries_export["batter"].isna().sum())
print("Missing bowlers:", deliveries_export["bowler"].isna().sum())

display(deliveries_export.head(10))

Deliveries exported: 9722
Missing batters: 0
Missing bowlers: 0

,match_id,innings,innings_name,batting_team,ball_label,batter,non_striker,bowler,batter_runs,total_runs,extra_runs,wide_runs,no_ball_runs,byes,leg_byes,penalty_runs,wicket_count,wicket_players
0,1415701,1,1st innings,Canada,0.1,A Johnson,NS Dhaliwal,Ali Khan,4,4,0,0,0,0,0,0,0,
1,1415701,1,1st innings,Canada,0.2,A Johnson,NS Dhaliwal,Ali Khan,0,0,0,0,0,0,0,0,0,
2,1415701,1,1st innings,Canada,0.3,A Johnson,NS Dhaliwal,Ali Khan,0,1,1,0,0,0,1,0,0,
3,1415701,1,1st innings,Canada,0.4,NS Dhaliwal,A Johnson,Ali Khan,0,0,0,0,0,0,0,0,0,
4,1415701,1,1st innings,Canada,0.5,NS Dhaliwal,A Johnson,Ali Khan,0,0,0,0,0,0,0,0,0,
5,1415701,1,1st innings,Canada,0.6,NS Dhaliwal,A Johnson,Ali Khan,1,1,0,0,0,0,0,0,0,
6,1415701,1,1st innings,Canada,1.1,NS Dhaliwal,A Johnson,SN Netravalkar,0,0,0,0,0,0,0,0,0,
7,1415701,1,1st innings,Canada,1.2,NS Dhaliwal,A Johnson,SN Netravalkar,4,4,0,0,0,0,0,0,0,
8,1415701,1,1st innings,Canada,1.3,NS Dhaliwal,A Johnson,SN Netravalkar,1,1,0,0,0,0,0,0,0,
9,1415701,1,1st innings,Canada,1.4,A Johnson,NS Dhaliwal,SN Netravalkar,1,1,0,0,0,0,0,0,0,

In [23]:

import pandas as pd
from pathlib import Path

project_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics"
)

cleaned_folder = project_folder / "02_Data" / "Cleaned"

# Reload the saved CSV to verify the actual file
deliveries = pd.read_csv(cleaned_folder / "deliveries.csv")
matches = pd.read_csv(cleaned_folder / "matches.csv")

print("Matches:", matches["match_id"].nunique())
print("Delivery records:", len(deliveries))

print("\nMissing values:")
print(
    deliveries[["batter", "bowler", "batting_team",
                "batter_runs", "total_runs"]].isna().sum()
)

print("\nDuplicate rows:", deliveries.duplicated().sum())

print("\nTotal batter runs:", deliveries["batter_runs"].sum())
print("Total runs:", deliveries["total_runs"].sum())

print("\nInnings distribution:")
print(deliveries.groupby("innings_name").size())

print("\nSample:")
display(deliveries.head())

Matches: 44
Delivery records: 9722

Missing values:
batter          0
bowler          0
batting_team    0
batter_runs     0
total_runs      0
dtype: int64

Duplicate rows: 0

Total batter runs: 10449
Total runs: 11135

Innings distribution:
innings_name
1st innings                            5232
2nd innings                            4461
Namibia Super Over                        6
Oman Super Over                           6
Pakistan Super Over                       8
United States of America Super Over       9
dtype: int64

Sample:

,match_id,innings,innings_name,batting_team,ball_label,batter,non_striker,bowler,batter_runs,total_runs,extra_runs,wide_runs,no_ball_runs,byes,leg_byes,penalty_runs,wicket_count,wicket_players
0,1415701,1,1st innings,Canada,0.1,A Johnson,NS Dhaliwal,Ali Khan,4,4,0,0,0,0,0,0,0,NaN
1,1415701,1,1st innings,Canada,0.2,A Johnson,NS Dhaliwal,Ali Khan,0,0,0,0,0,0,0,0,0,NaN
2,1415701,1,1st innings,Canada,0.3,A Johnson,NS Dhaliwal,Ali Khan,0,1,1,0,0,0,1,0,0,NaN
3,1415701,1,1st innings,Canada,0.4,NS Dhaliwal,A Johnson,Ali Khan,0,0,0,0,0,0,0,0,0,NaN
4,1415701,1,1st innings,Canada,0.5,NS Dhaliwal,A Johnson,Ali Khan,0,0,0,0,0,0,0,0,0,NaN

In [24]:

import pandas as pd
from pathlib import Path

# Use the validated delivery data
deliveries = pd.read_csv(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Cleaned\deliveries.csv"
)

# Exclude Super Overs from regular innings statistics
regular = deliveries[
    ~deliveries["innings_name"].str.contains(
        "Super Over", case=False, na=False
    )
].copy()

# Ensure numeric data types
for col in ["batter_runs", "wide_runs", "no_ball_runs"]:
    regular[col] = pd.to_numeric(
        regular[col], errors="coerce"
    ).fillna(0)

# Balls faced: wides do not count as balls faced
regular["balls_faced"] = (
    regular["wide_runs"] == 0
).astype(int)

# Boundaries credited to the batter
regular["fours"] = (regular["batter_runs"] == 4).astype(int)
regular["sixes"] = (regular["batter_runs"] == 6).astype(int)

# Aggregate player batting performance
batting_summary = (
    regular.groupby("batter")
    .agg(
        runs=("batter_runs", "sum"),
        balls_faced=("balls_faced", "sum"),
        fours=("fours", "sum"),
        sixes=("sixes", "sum")
    )
    .reset_index()
)

batting_summary["strike_rate"] = (
    batting_summary["runs"] /
    batting_summary["balls_faced"].replace(0, pd.NA) * 100
).round(2)

batting_summary = batting_summary.sort_values(
    ["runs", "strike_rate"], ascending=[False, False]
)

# Save processed output
project_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics"
)

processed_folder = project_folder / "02_Data" / "Processed"
processed_folder.mkdir(parents=True, exist_ok=True)

batting_summary.to_csv(
    processed_folder / "batting_summary.csv",
    index=False
)

print("Regular-innings deliveries:", len(regular))
print("Players in batting summary:", len(batting_summary))
print("\nTop 10 batters:")
display(batting_summary.head(10))

Regular-innings deliveries: 9693
Players in batting summary: 223

Top 10 batters:

         batter  runs  balls_faced  fours  sixes  strike_rate
210     TM Head   255          158     26     15       161.39
168   RG Sharma   249          151     23     15       164.90
158   Q de Kock   238          165     20     13       144.24
9      AGS Gous   219          145     20     11       151.03
80   JC Buttler   214          135     22     10       158.52
66    H Klaasen   190          150      9     13       126.67
151     PD Salt   188          118     16     10       159.32
47    DA Warner   175          120     17      9       145.83
46    DA Miller   169          165     10      8       102.42
205    T Stubbs   165          163     13      3       101.23

In [25]:

# Find the first delivery with a wicket in the raw YAML data

wicket_example = None

for file_path in yaml_files:
    if file_path.name not in set(matches_df["file_name"]):
        continue

    with open(file_path, "r", encoding="utf-8") as file:
        data = yaml.safe_load(file)

    for innings_entry in data.get("innings", []):
        innings_name, innings_data = next(iter(innings_entry.items()))

        for delivery_item in innings_data.get("deliveries", []):
            ball_label, ball_data = next(iter(delivery_item.items()))

            if "wicket" in ball_data or "wickets" in ball_data:
                wicket_example = {
                    "file": file_path.name,
                    "innings": innings_name,
                    "ball": ball_label,
                    "delivery": ball_data
                }
                break

        if wicket_example:
            break

    if wicket_example:
        break

if wicket_example:
    print("File:", wicket_example["file"])
    print("Innings:", wicket_example["innings"])
    print("Ball:", wicket_example["ball"])
    print("Delivery:", wicket_example["delivery"])
else:
    print("No wicket records found. We need to inspect the source schema.")

File: 1415701.yaml
Innings: 1st innings
Ball: 5.2
Delivery: {'actual_delivery': '5.2', 'non_striker': 'NS Dhaliwal', 'bowler': 'Harmeet Singh', 'runs': {'extras': 0, 'total': 0, 'batsman': 0}, 'batsman': 'A Johnson', 'wicket': {'player_out': 'A Johnson', 'fielders': ['NR Kumar'], 'kind': 'caught'}}

In [26]:

# Display the complete wicket information

delivery = wicket_example["delivery"]

print("Match file:", wicket_example["file"])
print("Ball:", wicket_example["ball"])
print("Bowler:", delivery.get("bowler"))

print("\nWicket details:")

if "wickets" in delivery:
    print(delivery["wickets"])
elif "wicket" in delivery:
    print(delivery["wicket"])
else:
    print("No wicket details found.")

print("\nRuns information:")
print(delivery.get("runs", {}))

Match file: 1415701.yaml
Ball: 5.2
Bowler: Harmeet Singh

Wicket details:
{'player_out': 'A Johnson', 'fielders': ['NR Kumar'], 'kind': 'caught'}

Runs information:
{'extras': 0, 'total': 0, 'batsman': 0}

In [27]:

import pandas as pd

# Start with the cleaned delivery-level dataset
df = deliveries_export.copy()

# Inspect the columns available
print("Available columns:")
print(df.columns.tolist())

Available columns:
['match_id', 'innings', 'innings_name', 'batting_team', 'ball_label', 'batter', 'non_striker', 'bowler', 'batter_runs', 'total_runs', 'extra_runs', 'wide_runs', 'no_ball_runs', 'byes', 'leg_byes', 'penalty_runs', 'wicket_count', 'wicket_players']

In [28]:

# Display every column name with its data type

for column in df.columns:
    print(f"{column}: {df[column].dtype}")

match_id: str
innings: int64
innings_name: str
batting_team: str
ball_label: str
batter: str
non_striker: str
bowler: str
batter_runs: int64
total_runs: int64
extra_runs: int64
wide_runs: int64
no_ball_runs: int64
byes: int64
leg_byes: int64
penalty_runs: int64
wicket_count: int64
wicket_players: str

In [29]:

print(df.columns.tolist())

['match_id', 'innings', 'innings_name', 'batting_team', 'ball_label', 'batter', 'non_striker', 'bowler', 'batter_runs', 'total_runs', 'extra_runs', 'wide_runs', 'no_ball_runs', 'byes', 'leg_byes', 'penalty_runs', 'wicket_count', 'wicket_players']

In [30]:
print(df.columns.tolist())

['match_id', 'innings', 'innings_name', 'batting_team', 'ball_label', 'batter', 'non_striker', 'bowler', 'batter_runs', 'total_runs', 'extra_runs', 'wide_runs', 'no_ball_runs', 'byes', 'leg_byes', 'penalty_runs', 'wicket_count', 'wicket_players']

In [31]:

# Bowling performance analysis

import pandas as pd

df = deliveries_export.copy()

# Exclude super-over deliveries for the main tournament analysis
regular_df = df[
    ~df["innings_name"].str.contains("Super Over", case=False, na=False)
].copy()

# Ensure run columns are numeric
run_columns = [
    "total_runs", "batter_runs", "extra_runs",
    "wide_runs", "no_ball_runs"
]

for col in run_columns:
    regular_df[col] = pd.to_numeric(
        regular_df[col], errors="coerce"
    ).fillna(0)

# Runs charged to the bowler exclude byes and leg-byes
regular_df["bowler_runs"] = (
    regular_df["total_runs"]
    - regular_df["byes"].fillna(0)
    - regular_df["leg_byes"].fillna(0)
)

# Legal deliveries exclude wides and no-balls
regular_df["legal_ball"] = (
    (regular_df["wide_runs"] == 0)
    & (regular_df["no_ball_runs"] == 0)
).astype(int)

# Wickets credited to the bowler
# Run outs, retired hurt, obstructing the field, etc. are excluded.
non_bowler_dismissals = {
    "run out",
    "retired hurt",
    "retired out",
    "obstructing the field",
    "handled the ball"
}

regular_df["bowler_wicket"] = 0

# This field contains wicket details as text in the cleaned dataset.
# Check dismissal types before counting credited wickets.
print("Columns:", regular_df.columns.tolist())
print("\nWicket examples:")
print(regular_df.loc[
    regular_df["wicket_count"] > 0,
    ["bowler", "wicket_count", "wicket_players"]
].head(10))

Columns: ['match_id', 'innings', 'innings_name', 'batting_team', 'ball_label', 'batter', 'non_striker', 'bowler', 'batter_runs', 'total_runs', 'extra_runs', 'wide_runs', 'no_ball_runs', 'byes', 'leg_byes', 'penalty_runs', 'wicket_count', 'wicket_players', 'bowler_runs', 'legal_ball', 'bowler_wicket']

Wicket examples:
               bowler  wicket_count wicket_players
31      Harmeet Singh             1      A Johnson
47   SC van Schalkwyk             1   Pargat Singh
84        CJ Anderson             1    NS Dhaliwal
107          Ali Khan             1      NR Kirton
114       CJ Anderson             1       DS Bajwa
123       Kaleem Sana             1      SR Taylor
163        D Heyliger             1       MD Patel
227           N Dutta             1       AGS Gous
251        R Shepherd             1         TP Ura
254         AJ Hosein             1        L Siaka

In [32]:

# Inspect all columns related to wickets and extras

wicket_columns = [
    col for col in regular_df.columns
    if any(word in col.lower() for word in [
        "wicket", "dismiss", "extra", "wide", "no_ball", "bye"
    ])
]

print("Wicket and extras columns:")
print(wicket_columns)

print("\nSample records containing wickets:")
display(
    regular_df.loc[
        regular_df["wicket_count"] > 0,
        wicket_columns + ["bowler", "match_id"]
    ].head(15)
)

Wicket and extras columns:
['extra_runs', 'wide_runs', 'no_ball_runs', 'byes', 'leg_byes', 'wicket_count', 'wicket_players', 'bowler_wicket']

Sample records containing wickets:

,extra_runs,wide_runs,no_ball_runs,byes,leg_byes,wicket_count,wicket_players,bowler_wicket,bowler,match_id
31,0,0,0,0,0,1,A Johnson,0,Harmeet Singh,1415701
47,0,0,0,0,0,1,Pargat Singh,0,SC van Schalkwyk,1415701
84,0,0,0,0,0,1,NS Dhaliwal,0,CJ Anderson,1415701
107,0,0,0,0,0,1,NR Kirton,0,Ali Khan,1415701
114,0,0,0,0,0,1,DS Bajwa,0,CJ Anderson,1415701
123,0,0,0,0,0,1,SR Taylor,0,Kaleem Sana,1415701
163,0,0,0,0,0,1,MD Patel,0,D Heyliger,1415701
227,0,0,0,0,0,1,AGS Gous,0,N Dutta,1415701
251,0,0,0,0,0,1,TP Ura,0,R Shepherd,1415702
254,0,0,0,0,0,1,L Siaka,0,AJ Hosein,1415702
280,0,0,0,0,0,1,A Vala,0,AS Joseph,1415702
298,0,0,0,0,0,1,H Hiri,0,G Motie,1415702
335,0,0,0,0,0,1,CJA Amini,0,AD Russell,1415702
345,0,0,0,0,0,1,S Bau,0,AS Joseph,1415702
360,0,0,0,0,0,1,CA Soper,0,AD Russell,1415702

In [33]:

# Inspect existing wicket attribution and its distribution

print("Wicket counts:")
print(regular_df["wicket_count"].value_counts(dropna=False))

print("\nBowler wicket counts:")
print(regular_df["bowler_wicket"].value_counts(dropna=False))

print("\nCompare total wickets and bowler wickets:")
print("Total wicket events:", regular_df["wicket_count"].sum())
print("Wickets credited to bowlers:", regular_df["bowler_wicket"].sum())

print("\nSample wicket records:")
display(
    regular_df.loc[
        regular_df["wicket_count"] > 0,
        ["match_id", "innings_name", "bowler",
         "wicket_count", "wicket_players", "bowler_wicket"]
    ].head(20)
)

Wicket counts:
wicket_count
0    9131
1     562
Name: count, dtype: int64

Bowler wicket counts:
bowler_wicket
0    9693
Name: count, dtype: int64

Compare total wickets and bowler wickets:
Total wicket events: 562
Wickets credited to bowlers: 0

Sample wicket records:

,match_id,innings_name,bowler,wicket_count,wicket_players,bowler_wicket
31,1415701,1st innings,Harmeet Singh,1,A Johnson,0
47,1415701,1st innings,SC van Schalkwyk,1,Pargat Singh,0
84,1415701,1st innings,CJ Anderson,1,NS Dhaliwal,0
107,1415701,1st innings,Ali Khan,1,NR Kirton,0
114,1415701,1st innings,CJ Anderson,1,DS Bajwa,0
123,1415701,2nd innings,Kaleem Sana,1,SR Taylor,0
163,1415701,2nd innings,D Heyliger,1,MD Patel,0
227,1415701,2nd innings,N Dutta,1,AGS Gous,0
251,1415702,1st innings,R Shepherd,1,TP Ura,0
254,1415702,1st innings,AJ Hosein,1,L Siaka,0
280,1415702,1st innings,AS Joseph,1,A Vala,0
298,1415702,1st innings,G Motie,1,H Hiri,0
335,1415702,1st innings,AD Russell,1,CJA Amini,0
345,1415702,1st innings,AS Joseph,1,S Bau,0
360,1415702,1st innings,AD Russell,1,CA Soper,0
363,1415702,1st innings,AS Joseph,1,A Nao,0
374,1415702,2nd innings,A Nao,1,J Charles,0
416,1415702,2nd innings,J Kariko,1,N Pooran,0
426,1415702,2nd innings,A Vala,1,BA King,0
451,1415702,2nd innings,CA Soper,1,R Powell,0

In [34]:

# Check how many wicket events are credited to bowlers

print("Total wicket events:", regular_df["wicket_count"].sum())

print(
    "Total bowler wickets:",
    regular_df["bowler_wicket"].sum()
)

print("\nBowler wicket distribution:")
print(regular_df["bowler_wicket"].value_counts(dropna=False))

print("\nWicket event examples:")
display(
    regular_df.loc[
        regular_df["wicket_count"] > 0,
        [
            "match_id",
            "bowler",
            "wicket_count",
            "wicket_players",
            "bowler_wicket"
        ]
    ].head(15)
)

Total wicket events: 562
Total bowler wickets: 0

Bowler wicket distribution:
bowler_wicket
0    9693
Name: count, dtype: int64

Wicket event examples:

    match_id            bowler  wicket_count wicket_players  bowler_wicket
31   1415701     Harmeet Singh             1      A Johnson              0
47   1415701  SC van Schalkwyk             1   Pargat Singh              0
84   1415701       CJ Anderson             1    NS Dhaliwal              0
107  1415701          Ali Khan             1      NR Kirton              0
114  1415701       CJ Anderson             1       DS Bajwa              0
123  1415701       Kaleem Sana             1      SR Taylor              0
163  1415701        D Heyliger             1       MD Patel              0
227  1415701           N Dutta             1       AGS Gous              0
251  1415702        R Shepherd             1         TP Ura              0
254  1415702         AJ Hosein             1        L Siaka              0
280  1415702         AS Joseph             1         A Vala              0
298  1415702           G Motie             1         H Hiri              0
335  1415702        AD Russell             1      CJA Amini              0
345  1415702         AS Joseph             1          S Bau              0
360  1415702        AD Russell             1       CA Soper              0

In [35]:

# Inspect all dismissal types in the raw YAML files

from collections import Counter

dismissal_types = Counter()

for match in yaml_files:
    with open(match, "r", encoding="utf-8") as file:
        match_data = yaml.safe_load(file)

    for innings in match_data.get("innings", []):
        for innings_name, innings_data in innings.items():
            deliveries = innings_data.get("deliveries", [])

            for delivery in deliveries:
                for wicket in delivery.get("wickets", []):
                    dismissal_types[wicket.get("kind", "unknown")] += 1

print("Dismissal types and frequencies:")

for kind, count in dismissal_types.most_common():
    print(f"{kind}: {count}")

print("\nTotal dismissal records:", sum(dismissal_types.values()))

Dismissal types and frequencies:

Total dismissal records: 0

In [36]:

from pathlib import Path

print("Number of YAML files:", len(yaml_files))
print("\nFirst 5 entries:")

for file in yaml_files[:5]:
    print(file)

print("\nPath checks:")

for file in yaml_files[:5]:
    print(file, "Exists:", Path(file).exists())

Number of YAML files: 230

First 5 entries:
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273712.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273713.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273714.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273715.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273716.yaml

Path checks:
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273712.yaml Exists: True
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273713.yaml Exists: True
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273714.yaml Exists: True
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273715.yaml Exists: True
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273716.yaml Exists: True

In [38]:

from pathlib import Path

extracted_folder = Path(r"C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted")

yaml_paths = list(extracted_folder.glob("*.yaml"))

print("Extracted YAML files found:", len(yaml_paths))
print("Sample paths:")

for path in yaml_paths[:5]:
    print(path)

Extracted YAML files found: 230
Sample paths:
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273712.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273713.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273714.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273715.yaml
C:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted\1273716.yaml

In [39]:

from collections import Counter
import yaml

dismissal_types = Counter()
files_processed = 0
files_failed = []

for path in yaml_paths:
    try:
        with open(path, "r", encoding="utf-8") as file:
            match_data = yaml.safe_load(file)

        if not isinstance(match_data, dict):
            continue

        files_processed += 1

        for innings in match_data.get("innings", []):
            for innings_name, innings_data in innings.items():
                for delivery in innings_data.get("deliveries", []):
                    for wicket in delivery.get("wickets", []):
                        kind = wicket.get("kind", "unknown")
                        dismissal_types[kind] += 1

    except Exception as error:
        files_failed.append((str(path), str(error)))

print("Files processed:", files_processed)
print("Files failed:", len(files_failed))
print("\nDismissal types and counts:")

for kind, count in dismissal_types.most_common():
    print(f"{kind}: {count}")

print("\nTotal dismissal records:", sum(dismissal_types.values()))

Files processed: 230
Files failed: 0

Dismissal types and counts:

Total dismissal records: 0

In [40]:

import yaml

# Inspect one source file directly
sample_path = yaml_paths[0]

with open(sample_path, "r", encoding="utf-8") as file:
    sample_match = yaml.safe_load(file)

print("File:", sample_path.name)
print("\nTop-level keys:")
print(sample_match.keys())

print("\nFirst innings structure:")
first_innings = sample_match["innings"][0]
print(first_innings.keys())

print("\nFirst innings data:")
print(first_innings)

File: 1273712.yaml

Top-level keys:
dict_keys(['meta', 'info', 'innings'])

First innings structure:
dict_keys(['1st innings'])

First innings data:

In [41]:

# Extract the first delivery from the first innings

first_innings_data = first_innings["1st innings"]
first_delivery = first_innings_data["deliveries"][0]

print("First delivery type:", type(first_delivery))
print("First delivery contents:")
print(first_delivery)

print("\nDelivery keys:")
print(first_delivery.keys())

print("\nWickets field:")
print(first_delivery.get("wickets", "KEY NOT PRESENT"))

First delivery type: <class 'dict'>
First delivery contents:
{0.1: {'actual_delivery': '0.1', 'non_striker': 'L Siaka', 'bowler': 'Bilal Khan', 'runs': {'extras': 0, 'total': 0, 'batsman': 0}, 'batsman': 'TP Ura'}}

Delivery keys:
dict_keys([0.1])

Wickets field:
KEY NOT PRESENT

In [42]:

# Find a delivery containing a wicket in the raw YAML data

wicket_example = None

for path in yaml_paths:
    with open(path, "r", encoding="utf-8") as file:
        match_data = yaml.safe_load(file)

    for innings in match_data.get("innings", []):
        for innings_name, innings_data in innings.items():
            for delivery in innings_data.get("deliveries", []):
                for ball_label, ball_data in delivery.items():
                    if isinstance(ball_data, dict) and ball_data.get("wickets"):
                        wicket_example = {
                            "file": path.name,
                            "innings": innings_name,
                            "ball": ball_label,
                            "delivery": ball_data
                        }
                        break

                if wicket_example:
                    break
            if wicket_example:
                break
        if wicket_example:
            break

    if wicket_example:
        break

if wicket_example:
    print("File:", wicket_example["file"])
    print("Innings:", wicket_example["innings"])
    print("Ball:", wicket_example["ball"])
    print("Delivery:", wicket_example["delivery"])
else:
    print("No wicket records found in the raw YAML files.")

No wicket records found in the raw YAML files.

In [43]:

from pathlib import Path
import yaml
from collections import Counter

extracted_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20 World Cup Cricket Analytics\02_Data\Extracted"
)

dismissal_types = Counter()
dismissal_records = []
files_processed = 0
files_failed = []

for path in extracted_folder.glob("*.yaml"):
    try:
        with path.open("r", encoding="utf-8") as file:
            match_data = yaml.safe_load(file)

        files_processed += 1

        if not isinstance(match_data, dict):
            continue

        innings_data = match_data.get("innings", {})

        for innings_name, innings_info in innings_data.items():
            if not isinstance(innings_info, dict):
                continue

            for over_label, delivery in innings_info.get(
                "deliveries", []
            ):
                if not isinstance(delivery, dict):
                    continue

                # Your YAML uses "wicket" (singular).
                wicket = delivery.get("wicket")

                if isinstance(wicket, dict):
                    dismissal_type = wicket.get("kind", "unknown")

                    dismissal_records.append({
                        "match_id": path.stem,
                        "innings": innings_name,
                        "ball_label": str(over_label),
                        "actual_delivery": delivery.get("actual_delivery"),
                        "batter": delivery.get("batsman"),
                        "bowler": delivery.get("bowler"),
                        "player_out": wicket.get("player_out"),
                        "dismissal_type": dismissal_type,
                        "fielders": wicket.get("fielders", [])
                    })

                    dismissal_types[dismissal_type] += 1

    except Exception as error:
        files_failed.append((path.name, str(error)))

print("Files processed:", files_processed)
print("Files failed:", len(files_failed))
print("Total dismissal records:", len(dismissal_records))
print("\nDismissal types:")

for dismissal_type, count in dismissal_types.most_common():
    print(f"{dismissal_type}: {count}")

print("\nSample dismissal records:")

for record in dismissal_records[:10]:
    print(record)

Files processed: 0
Files failed: 0
Total dismissal records: 0

Dismissal types:

Sample dismissal records:

In [44]:

from pathlib import Path
import yaml
from pprint import pprint

extracted_folder = Path(
    r"C:\Users\reddy\OneDrive\Documents\T20 World Cup Cricket Analytics\02_Data\Extracted"
)

sample_path = extracted_folder / "682899.yaml"

with sample_path.open("r", encoding="utf-8") as file:
    sample_match = yaml.safe_load(file)

print("Top-level keys:")
print(list(sample_match.keys()))

print("\nInnings keys:")
print(list(sample_match["innings"].keys()))

innings_name = "1st innings"
innings_data = sample_match["innings"][innings_name]

print("\nInnings-level keys:")
print(list(innings_data.keys()))

print("\nDelivery structure:")
pprint(innings_data["deliveries"][0])

print("\nFind deliveries containing a wicket:")
found = 0

for over in innings_data["deliveries"]:
    print("Over item type:", type(over).__name__)

    if isinstance(over, dict):
        for ball_label, delivery in over.items():
            if isinstance(delivery, dict) and "wicket" in delivery:
                print("\nBall label:", ball_label)
                pprint(delivery)
                found += 1

    if found:
        break

print("\nWicket deliveries found in this innings:", found)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\reddy\\OneDrive\\Documents\\T20 World Cup Cricket Analytics\\02_Data\\Extracted\\682899.yaml'

In [45]:

from pathlib import Path

# Locate the project from the current notebook working directory
current = Path.cwd()

print("Current working directory:", current)

# Search the current directory and its parents for the Extracted folder
project_root = next(
    (
        path for path in [current, *current.parents]
        if (path / "02_Data" / "Extracted").is_dir()
    ),
    None
)

if project_root is None:
    raise FileNotFoundError(
        "Could not locate 02_Data/Extracted. "
        "Check the notebook's working directory."
    )

extracted_folder = project_root / "02_Data" / "Extracted"

print("Project root:", project_root)
print("Extracted folder:", extracted_folder)
print("Number of YAML files:", len(list(extracted_folder.glob("*.yaml"))))

# Inspect the sample file
sample_path = extracted_folder / "682899.yaml"

print("Sample file exists:", sample_path.exists())

# If this file isn't in your current extracted dataset, show available files
if not sample_path.exists():
    print("Sample YAML files:")
    for path in list(extracted_folder.glob("*.yaml"))[:10]:
        print(path.name)

Current working directory: c:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\03_Python_Analysis
Project root: c:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics
Extracted folder: c:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Extracted
Number of YAML files: 230
Sample file exists: True

In [47]:

from pprint import pprint

print("Type of innings:", type(sample_match["innings"]).__name__)
print("Number of innings entries:", len(sample_match["innings"]))

print("\nFirst innings entry:")
pprint(sample_match["innings"][0])

print("\nKeys inside the first innings entry:")
print(list(sample_match["innings"][0].keys()))

print("\nFirst innings content:")
first_innings_entry = sample_match["innings"][0]
pprint(first_innings_entry, depth=4)

Type of innings: list
Number of innings entries: 2

First innings entry:
{'1st innings': {'deliveries': [{0.1: {'actual_delivery': '0.1',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 3,
                                                'extras': 0,
                                                'total': 3}}},
                                {0.2: {'actual_delivery': '0.2',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {0.3: {'actual_delivery': '0.3',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {0.4: {'actual_delivery': '0.4',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {0.5: {'actual_delivery': '0.5',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 4,
                                                'extras': 0,
                                                'total': 4}}},
                                {0.6: {'actual_delivery': '0.6',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {1.1: {'actual_delivery': '1.1',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {1.2: {'actual_delivery': '1.2',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {1.3: {'actual_delivery': '1.3',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {1.4: {'actual_delivery': '1.4',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {1.5: {'actual_delivery': '1.5',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {1.6: {'actual_delivery': '1.6',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 4,
                                                'extras': 0,
                                                'total': 4}}},
                                {2.1: {'actual_delivery': '2.1',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {2.2: {'actual_delivery': '2.2',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {2.3: {'actual_delivery': '2.3',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {2.4: {'actual_delivery': '2.4',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {2.5: {'actual_delivery': '2.5',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 4,
                                                'extras': 0,
                                                'total': 4}}},
                                {2.6: {'actual_delivery': '2.6',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Tanwir Afzal',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {3.1: {'actual_delivery': '3.1',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Najeeb Amar',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 4,
                                                'extras': 0,
                                                'total': 4}}},
                                {3.2: {'actual_delivery': '3.2',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Najeeb Amar',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {3.3: {'actual_delivery': '3.3',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Najeeb Amar',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {3.4: {'actual_delivery': '3.4',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Najeeb Amar',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 4,
                                                'extras': 0,
                                                'total': 4}}},
                                {3.5: {'actual_delivery': '3.5',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Najeeb Amar',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {3.6: {'actual_delivery': '3.6',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Najeeb Amar',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {4.1: {'actual_delivery': '4.1',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 4,
                                                'extras': 0,
                                                'total': 4}}},
                                {4.2: {'actual_delivery': '4.2',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {4.3: {'actual_delivery': '4.3',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'extras': {'wides': 1},
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 0,
                                                'extras': 1,
                                                'total': 1}}},
                                {4.4: {'actual_delivery': '4.3',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'Sagar Pun',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {4.5: {'actual_delivery': '4.4',
                                       'batsman': 'Sagar Pun',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0},
                                       'wicket': {'fielders': ['Waqas Barkat'],
                                                  'kind': 'caught',
                                                  'player_out': 'Sagar Pun'}}},
                                {4.6: {'actual_delivery': '4.5',
                                       'batsman': 'G Malla',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {4.7: {'actual_delivery': '4.6',
                                       'batsman': 'G Malla',
                                       'bowler': 'Haseeb Amjad',
                                       'non_striker': 'SP Khakurel',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {5.1: {'actual_delivery': '5.1',
                                       'batsman': 'SP Khakurel',
                                       'bowler': 'Nadeem Ahmed',
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0},
                                       'wicket': {'fielders': ['Aizaz Khan'],
                                                  'kind': 'caught',
                                                  'player_out': 'SP '
                                                                'Khakurel'}}},
                                {5.2: {'actual_delivery': '5.2',
                                       'batsman': 'P Khadka',
                                       'bowler': 'Nadeem Ahmed',
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {5.3: {'actual_delivery': '5.3',
                                       'batsman': 'P Khadka',
                                       'bowler': 'Nadeem Ahmed',
                                       'extras': {'wides': 1},
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 0,
                                                'extras': 1,
                                                'total': 1}}},
                                {5.4: {'actual_delivery': '5.3',
                                       'batsman': 'P Khadka',
                                       'bowler': 'Nadeem Ahmed',
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 4,
                                                'extras': 0,
                                                'total': 4}}},
                                {5.5: {'actual_delivery': '5.4',
                                       'batsman': 'P Khadka',
                                       'bowler': 'Nadeem Ahmed',
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {5.6: {'actual_delivery': '5.5',
                                       'batsman': 'P Khadka',
                                       'bowler': 'Nadeem Ahmed',
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 3,
                                                'extras': 0,
                                                'total': 3}}},
                                {5.7: {'actual_delivery': '5.6',
                                       'batsman': 'G Malla',
                                       'bowler': 'Nadeem Ahmed',
                                       'non_striker': 'P Khadka',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {6.1: {'actual_delivery': '6.1',
                                       'batsman': 'P Khadka',
                                       'bowler': 'Irfan Ahmed',
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {6.2: {'actual_delivery': '6.2',
                                       'batsman': 'G Malla',
                                       'bowler': 'Irfan Ahmed',
                                       'non_striker': 'P Khadka',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {6.3: {'actual_delivery': '6.3',
                                       'batsman': 'G Malla',
                                       'bowler': 'Irfan Ahmed',
                                       'non_striker': 'P Khadka',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {6.4: {'actual_delivery': '6.4',
                                       'batsman': 'G Malla',
                                       'bowler': 'Irfan Ahmed',
                                       'non_striker': 'P Khadka',
                                       'runs': {'batsman': 1,
                                                'extras': 0,
                                                'total': 1}}},
                                {6.5: {'actual_delivery': '6.5',
                                       'batsman': 'P Khadka',
                                       'bowler': 'Irfan Ahmed',
                                       'non_striker': 'G Malla',
                                       'runs': {'batsman': 0,
                                                'extras': 0,
                                                'total': 0}}},
                                {6.6: {'actual_delivery': '6.6',

In [48]:

from pprint import pprint

sample_path = extracted_folder / "682899.yaml"

with sample_path.open("r", encoding="utf-8") as file:
    sample_match = yaml.safe_load(file)

dismissals = []

for innings_entry in sample_match["innings"]:
    for innings_name, innings_data in innings_entry.items():

        if not isinstance(innings_data, dict):
            continue

        deliveries = innings_data.get("deliveries", [])

        for delivery_over in deliveries:
            for ball_label, delivery in delivery_over.items():

                wicket = delivery.get("wicket")

                if isinstance(wicket, dict):
                    dismissals.append({
                        "innings": innings_name,
                        "team": innings_data.get("team"),
                        "ball_label": str(ball_label),
                        "actual_delivery": delivery.get("actual_delivery"),
                        "batter": delivery.get("batsman"),
                        "bowler": delivery.get("bowler"),
                        "player_out": wicket.get("player_out"),
                        "dismissal_type": wicket.get("kind"),
                        "fielders": wicket.get("fielders", [])
                    })

print("Match:", sample_path.name)
print("Dismissal records found:", len(dismissals))

print("\nDismissal records:")
for dismissal in dismissals:
    pprint(dismissal)

print("\nDismissal type counts:")
from collections import Counter

print(Counter(
    d["dismissal_type"] for d in dismissals
))

Match: 682899.yaml
Dismissal records found: 18

Dismissal records:
{'actual_delivery': '4.4',
 'ball_label': '4.5',
 'batter': 'Sagar Pun',
 'bowler': 'Haseeb Amjad',
 'dismissal_type': 'caught',
 'fielders': ['Waqas Barkat'],
 'innings': '1st innings',
 'player_out': 'Sagar Pun',
 'team': 'Nepal'}
{'actual_delivery': '5.1',
 'ball_label': '5.1',
 'batter': 'SP Khakurel',
 'bowler': 'Nadeem Ahmed',
 'dismissal_type': 'caught',
 'fielders': ['Aizaz Khan'],
 'innings': '1st innings',
 'player_out': 'SP Khakurel',
 'team': 'Nepal'}
{'actual_delivery': '16.2',
 'ball_label': '16.2',
 'batter': 'P Khadka',
 'bowler': 'Najeeb Amar',
 'dismissal_type': 'caught',
 'fielders': ['Nizakat Khan'],
 'innings': '1st innings',
 'player_out': 'P Khadka',
 'team': 'Nepal'}
{'actual_delivery': '17.1',
 'ball_label': '17.1',
 'batter': 'B Bhandari',
 'bowler': 'Nadeem Ahmed',
 'dismissal_type': 'caught',
 'fielders': ['Waqas Barkat'],
 'innings': '1st innings',
 'player_out': 'B Bhandari',
 'team': 'Nepal'}
{'actual_delivery': '19.3',
 'ball_label': '19.3',
 'batter': 'G Malla',
 'bowler': 'Haseeb Amjad',
 'dismissal_type': 'caught and bowled',
 'fielders': [],
 'innings': '1st innings',
 'player_out': 'G Malla',
 'team': 'Nepal'}
{'actual_delivery': '19.4',
 'ball_label': '19.4',
 'batter': 'S Vesawkar',
 'bowler': 'Haseeb Amjad',
 'dismissal_type': 'run out',
 'fielders': ['Aizaz Khan', 'JJ Atkinson'],
 'innings': '1st innings',
 'player_out': 'S Vesawkar',
 'team': 'Nepal'}
{'actual_delivery': '19.5',
 'ball_label': '19.5',
 'batter': 'NB Budayair',
 'bowler': 'Haseeb Amjad',
 'dismissal_type': 'bowled',
 'fielders': [],
 'innings': '1st innings',
 'player_out': 'NB Budayair',
 'team': 'Nepal'}
{'actual_delivery': '19.6',
 'ball_label': '19.6',
 'batter': 'SP Gauchan',
 'bowler': 'Haseeb Amjad',
 'dismissal_type': 'run out',
 'fielders': ['Haseeb Amjad'],
 'innings': '1st innings',
 'player_out': 'SP Gauchan',
 'team': 'Nepal'}
{'actual_delivery': '0.1',
 'ball_label': '0.1',
 'batter': 'Irfan Ahmed',
 'bowler': 'P Khadka',
 'dismissal_type': 'caught',
 'fielders': ['SP Khakurel'],
 'innings': '2nd innings',
 'player_out': 'Irfan Ahmed',
 'team': 'Hong Kong'}
{'actual_delivery': '1.6',
 'ball_label': '1.6',
 'batter': 'JJ Atkinson',
 'bowler': 'Sompal Kami',
 'dismissal_type': 'bowled',
 'fielders': [],
 'innings': '2nd innings',
 'player_out': 'JJ Atkinson',
 'team': 'Hong Kong'}
{'actual_delivery': '6.4',
 'ball_label': '6.4',
 'batter': 'Waqas Barkat',
 'bowler': 'SP Gauchan',
 'dismissal_type': 'caught',
 'fielders': ['JK Mukhiya'],
 'innings': '2nd innings',
 'player_out': 'Waqas Barkat',
 'team': 'Hong Kong'}
{'actual_delivery': '10.3',
 'ball_label': '10.3',
 'batter': 'MS Chapman',
 'bowler': 'B Regmi',
 'dismissal_type': 'bowled',
 'fielders': [],
 'innings': '2nd innings',
 'player_out': 'MS Chapman',
 'team': 'Hong Kong'}
{'actual_delivery': '10.4',
 'ball_label': '10.4',
 'batter': 'Nizakat Khan',
 'bowler': 'B Regmi',
 'dismissal_type': 'bowled',
 'fielders': [],
 'innings': '2nd innings',
 'player_out': 'Nizakat Khan',
 'team': 'Hong Kong'}
{'actual_delivery': '11.1',
 'ball_label': '11.1',
 'batter': 'Babar Hayat',
 'bowler': 'SP Gauchan',
 'dismissal_type': 'bowled',
 'fielders': [],
 'innings': '2nd innings',
 'player_out': 'Babar Hayat',
 'team': 'Hong Kong'}
{'actual_delivery': '11.4',
 'ball_label': '11.4',
 'batter': 'Aizaz Khan',
 'bowler': 'SP Gauchan',
 'dismissal_type': 'bowled',
 'fielders': [],
 'innings': '2nd innings',
 'player_out': 'Aizaz Khan',
 'team': 'Hong Kong'}
{'actual_delivery': '12.3',
 'ball_label': '12.3',
 'batter': 'Tanwir Afzal',
 'bowler': 'B Regmi',
 'dismissal_type': 'caught',
 'fielders': ['P Khadka'],
 'innings': '2nd innings',
 'player_out': 'Tanwir Afzal',
 'team': 'Hong Kong'}
{'actual_delivery': '13.6',
 'ball_label': '13.6',
 'batter': 'Najeeb Amar',
 'bowler': 'Sompal Kami',
 'dismissal_type': 'caught',
 'fielders': ['SP Khakurel'],
 'innings': '2nd innings',
 'player_out': 'Najeeb Amar',
 'team': 'Hong Kong'}
{'actual_delivery': '16.6',
 'ball_label': '16.6',
 'batter': 'Nadeem Ahmed',
 'bowler': 'JK Mukhiya',
 'dismissal_type': 'bowled',
 'fielders': [],
 'innings': '2nd innings',
 'player_out': 'Nadeem Ahmed',
 'team': 'Hong Kong'}

Dismissal type counts:
Counter({'caught': 8, 'bowled': 7, 'run out': 2, 'caught and bowled': 1})

In [49]:

from pathlib import Path
from collections import Counter
import yaml

dismissal_types = Counter()
files_processed = 0
files_failed = []
total_dismissals = 0
total_bowler_credited = 0

for path in extracted_folder.glob("*.yaml"):
    try:
        with path.open("r", encoding="utf-8") as file:
            match = yaml.safe_load(file)

        if not isinstance(match, dict):
            continue

        files_processed += 1

        for innings_entry in match.get("innings", []):
            if not isinstance(innings_entry, dict):
                continue

            for innings_name, innings_data in innings_entry.items():
                if not isinstance(innings_data, dict):
                    continue

                for delivery_over in innings_data.get("deliveries", []):
                    if not isinstance(delivery_over, dict):
                        continue

                    for ball_label, delivery in delivery_over.items():
                        if not isinstance(delivery, dict):
                            continue

                        wicket = delivery.get("wicket")

                        if not isinstance(wicket, dict):
                            continue

                        kind = wicket.get("kind", "unknown")
                        dismissal_types[kind] += 1
                        total_dismissals += 1

                        # These dismissal types are not credited
                        # to the bowler in standard cricket scoring.
                        non_bowler_dismissals = {
                            "retired hurt",
                            "obstructing the field",
                            "run out",
                            "retired out",
                            "handled the ball",
                        }

                        if kind not in non_bowler_dismissals:
                            total_bowler_credited += 1

    except Exception as error:
        files_failed.append((path.name, str(error)))

print("Files processed:", files_processed)
print("Files failed:", len(files_failed))
print("Total dismissal records:", total_dismissals)
print("Bowler-credited dismissals (provisional):",
      total_bowler_credited)

print("\nDismissal types:")
for kind, count in dismissal_types.most_common():
    print(f"{kind}: {count}")

if files_failed:
    print("\nFailed files (first 10):")
    for item in files_failed[:10]:
        print(item)

Files processed: 230
Files failed: 0
Total dismissal records: 2901
Bowler-credited dismissals (provisional): 2694

Dismissal types:
caught: 1766
bowled: 552
lbw: 207
run out: 198
stumped: 88
caught and bowled: 77
retired hurt: 7
hit wicket: 4
retired out: 2

In [50]:

print("Unique dismissal types:", len(dismissal_types))

print("\nAll dismissal types and counts:")
for kind, count in sorted(dismissal_types.items()):
    print(f"{kind}: {count}")

print("\nTotal dismissal records:", sum(dismissal_types.values()))

Unique dismissal types: 9

All dismissal types and counts:
bowled: 552
caught: 1766
caught and bowled: 77
hit wicket: 4
lbw: 207
retired hurt: 7
retired out: 2
run out: 198
stumped: 88

Total dismissal records: 2901

In [51]:

import pandas as pd
import yaml
from collections import defaultdict

bowling_stats = defaultdict(lambda: {
    "wickets": 0,
    "runs_conceded": 0,
    "legal_balls": 0,
    "matches": set()
})

# Dismissals that are not credited to the bowler
non_bowler_dismissals = {
    "run out",
    "retired hurt",
    "retired out",
    "obstructing the field",
}

for path in extracted_folder.glob("*.yaml"):
    with path.open("r", encoding="utf-8") as file:
        match = yaml.safe_load(file)

    if not isinstance(match, dict):
        continue

    match_id = path.stem

    for innings_entry in match.get("innings", []):
        if not isinstance(innings_entry, dict):
            continue

        for innings_name, innings_data in innings_entry.items():
            if not isinstance(innings_data, dict):
                continue

            for delivery_over in innings_data.get("deliveries", []):
                if not isinstance(delivery_over, dict):
                    continue

                for ball_label, delivery in delivery_over.items():
                    if not isinstance(delivery, dict):
                        continue

                    bowler = delivery.get("bowler")
                    if not bowler:
                        continue

                    stats = bowling_stats[bowler]
                    stats["matches"].add(match_id)

                    runs = delivery.get("runs", {})
                    extras = delivery.get("extras", {})

                    # Runs charged to the bowler:
                    # exclude byes and leg-byes.
                    bowler_runs = runs.get("total", 0)
                    bowler_runs -= extras.get("byes", 0)
                    bowler_runs -= extras.get("legbyes", 0)
                    bowler_runs -= extras.get("penalty", 0)

                    stats["runs_conceded"] += bowler_runs

                    # Legal deliveries exclude wides and no-balls.
                    if "wides" not in extras and "noballs" not in extras:
                        stats["legal_balls"] += 1

                    wicket = delivery.get("wicket", {})
                    if isinstance(wicket, dict) and wicket:
                        kind = wicket.get("kind", "").lower()

                        if kind and kind not in non_bowler_dismissals:
                            stats["wickets"] += 1

bowling_summary = pd.DataFrame([
    {
        "bowler": bowler,
        "matches": len(stats["matches"]),
        "wickets": stats["wickets"],
        "runs_conceded": stats["runs_conceded"],
        "legal_balls": stats["legal_balls"],
    }
    for bowler, stats in bowling_stats.items()
])

bowling_summary["overs"] = (
    bowling_summary["legal_balls"] // 6
    + (bowling_summary["legal_balls"] % 6) / 10
)

bowling_summary["economy"] = (
    bowling_summary["runs_conceded"]
    / (bowling_summary["legal_balls"] / 6).replace(0, float("nan"))
)

bowling_summary["bowling_average"] = (
    bowling_summary["runs_conceded"]
    / bowling_summary["wickets"].replace(0, float("nan"))
)

bowling_summary = bowling_summary.sort_values(
    ["wickets", "economy"],
    ascending=[False, True]
)

display(bowling_summary.head(15))
print("Unique bowlers:", bowling_summary["bowler"].nunique())

,bowler,matches,wickets,runs_conceded,legal_balls,overs,economy,bowling_average
63,A Zampa,23,40,559,512,85.2,6.550781,13.975000
73,AU Rashid,32,39,839,702,117.0,7.170940,21.512821
40,PWH de Silva,19,37,446,434,72.2,6.165899,12.054054
91,JJ Bumrah,24,36,514,530,88.2,5.818868,14.277778
65,A Nortje,20,36,449,462,77.0,5.831169,12.472222
16,Shakib Al Hasan,28,35,702,596,99.2,7.067114,20.057143
153,Arshdeep Singh,21,33,589,456,76.0,7.750000,17.848485
111,HH Pandya,28,33,775,540,90.0,8.611111,23.484848
83,Shaheen Shah Afridi,21,30,586,469,78.1,7.496802,19.533333
72,CJ Jordan,22,30,571,421,70.1,8.137767,19.033333
100,TA Boult,16,29,386,382,63.4,6.062827,13.310345
38,M Theekshana,24,29,563,520,86.4,6.496154,19.413793
64,K Rabada,26,28,754,562,93.4,8.049822,26.928571
98,MJ Santner,25,27,579,551,91.5,6.304900,21.444444
14,Mustafizur Rahman,21,27,545,468,78.0,6.987179,20.185185

Unique bowlers: 451

In [52]:

print("BOWLING DATA VALIDATION")
print("-" * 40)

print("Unique bowlers:", bowling_summary["bowler"].nunique())

print("Total bowler wickets:",
      bowling_summary["wickets"].sum())

print("Expected bowler-credited dismissals:",
      sum(dismissal_types.values())
      - dismissal_types.get("run out", 0)
      - dismissal_types.get("retired hurt", 0)
      - dismissal_types.get("retired out", 0))

print("Total legal balls:",
      bowling_summary["legal_balls"].sum())

print("Total runs conceded:",
      bowling_summary["runs_conceded"].sum())

print("\nTop 10 bowlers:")
display(
    bowling_summary[
        ["bowler", "matches", "wickets",
         "runs_conceded", "legal_balls",
         "economy", "bowling_average"]
    ].head(10).round(2)
)

BOWLING DATA VALIDATION
----------------------------------------
Unique bowlers: 451
Total bowler wickets: 2694
Expected bowler-credited dismissals: 2694
Total legal balls: 50610
Total runs conceded: 64061

Top 10 bowlers:

,bowler,matches,wickets,runs_conceded,legal_balls,economy,bowling_average
63,A Zampa,23,40,559,512,6.55,13.98
73,AU Rashid,32,39,839,702,7.17,21.51
40,PWH de Silva,19,37,446,434,6.17,12.05
91,JJ Bumrah,24,36,514,530,5.82,14.28
65,A Nortje,20,36,449,462,5.83,12.47
16,Shakib Al Hasan,28,35,702,596,7.07,20.06
153,Arshdeep Singh,21,33,589,456,7.75,17.85
111,HH Pandya,28,33,775,540,8.61,23.48
83,Shaheen Shah Afridi,21,30,586,469,7.50,19.53
72,CJ Jordan,22,30,571,421,8.14,19.03

In [53]:

from pathlib import Path

processed_folder = extracted_folder.parent / "Processed"
processed_folder.mkdir(parents=True, exist_ok=True)

output_path = processed_folder / "bowling_summary.csv"

bowling_summary.to_csv(output_path, index=False)

print("Saved to:", output_path)
print("Rows:", len(bowling_summary))
print("Columns:", bowling_summary.columns.tolist())
print("File exists:", output_path.exists())

Saved to: c:\Users\reddy\OneDrive\Documents\T20_World_Cup_Cricket_Analytics\02_Data\Processed\bowling_summary.csv
Rows: 451
Columns: ['bowler', 'matches', 'wickets', 'runs_conceded', 'legal_balls', 'overs', 'economy', 'bowling_average']
File exists: True

In [54]:

from pathlib import Path
import pandas as pd

processed_folder = extracted_folder.parent / "Processed"

for filename in ["batting_summary.csv", "bowling_summary.csv"]:
    file_path = processed_folder / filename

    print(f"\n{filename}")
    print("Exists:", file_path.exists())

    if file_path.exists():
        df = pd.read_csv(file_path)
        print("Rows:", len(df))
        print("Columns:", df.columns.tolist())
        display(df.head(3))

batting_summary.csv
Exists: True
Rows: 223
Columns: ['batter', 'runs', 'balls_faced', 'fours', 'sixes', 'strike_rate']

      batter  runs  balls_faced  fours  sixes  strike_rate
0    TM Head   255          158     26     15       161.39
1  RG Sharma   249          151     23     15       164.90
2  Q de Kock   238          165     20     13       144.24

bowling_summary.csv
Exists: True
Rows: 451
Columns: ['bowler', 'matches', 'wickets', 'runs_conceded', 'legal_balls', 'overs', 'economy', 'bowling_average']

,bowler,matches,wickets,runs_conceded,legal_balls,overs,economy,bowling_average
0,A Zampa,23,40,559,512,85.2,6.550781,13.975000
1,AU Rashid,32,39,839,702,117.0,7.170940,21.512821
2,PWH de Silva,19,37,446,434,72.2,6.165899,12.054054